import os
def nfs():
    os.system("yum install nfs-utils")
    storagepath=input("Enter path of network storage device : ")
    os.system("mkdir {}".format(storagepath))
    os.system("vim /etc/exports")
    os.system("systemctl restart nfs-server")
    os.system("systemctl enable nfs-server")
    print("Service nfs-server successfully restart and enable...")
    os.system("exportfs -v")
    print("Now configuring the NFS at client side...")
    server_ip=input("Enter Server IP address : ")
    client_ip=input("Enter Client IP address : ")
    mountpath=input("Enter the path of directory that u want to mount on storage device : ")
    os.system("ssh {0} mkdir {1}".format(client_ip,mountpath))
    os.system("ssh {0} mount {1}:{2} {3}".format(client_ip,server_ip,storagepath,mountpath))
    os.system("ssh {0} df -hT".format(client_ip))
    print("Successfully mounted")
    exit()
